// <auto-generated />
using System;
using Employment_advertisement_project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Employment_advertisement_project.Migrations
{
    [DbContext(typeof(EAPdatabase))]
    partial class EAPdatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Employment_advertisement_project.Model.Apply_job_detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Candidate_availabilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Candidate_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Candidate_notice_period")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Candidate_objID")
                        .HasColumnType("int");

                    b.Property<int>("Job_id")
                        .HasColumnType("int");

                    b.Property<int?>("Job_objID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Candidate_objID");

                    b.HasIndex("Job_objID");

                    b.ToTable("Apply_job_detail");
                });

            modelBuilder.Entity("Employment_advertisement_project.Model.Candidate_detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DOB_of_candidate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email_address_of_candidate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile_no_of_candidate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_of_candidate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Candidate_detail");
                });

            modelBuilder.Entity("Employment_advertisement_project.Model.Employer_detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address_of_employer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_of_establishment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Employer_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employer_detail");
                });

            modelBuilder.Entity("Employment_advertisement_project.Model.Job_detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Employer_id")
                        .HasColumnType("int");

                    b.Property<int?>("Employer_objID")
                        .HasColumnType("int");

                    b.Property<string>("Job_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Job_salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Job_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Employer_objID");

                    b.ToTable("Job_detail");
                });

            modelBuilder.Entity("Employment_advertisement_project.Model.Apply_job_detail", b =>
                {
                    b.HasOne("Employment_advertisement_project.Model.Candidate_detail", "Candidate_obj")
                        .WithMany()
                        .HasForeignKey("Candidate_objID");

                    b.HasOne("Employment_advertisement_project.Model.Job_detail", "Job_obj")
                        .WithMany()
                        .HasForeignKey("Job_objID");

                    b.Navigation("Candidate_obj");

                    b.Navigation("Job_obj");
                });

            modelBuilder.Entity("Employment_advertisement_project.Model.Job_detail", b =>
                {
                    b.HasOne("Employment_advertisement_project.Model.Employer_detail", "Employer_obj")
                        .WithMany()
                        .HasForeignKey("Employer_objID");

                    b.Navigation("Employer_obj");
                });
#pragma warning restore 612, 618
        }
    }
}
